### ISSUE TITLE
Problems when hosting

### ISSUE THREAD

**Issue by Puky96** [jsreport/jsreport-dotnet-example-webapp#1]
This is really helpful for generating reports. 

Do you have this hosted anywhere? Because for me, it`s working perfectly locally, when run from Visual Studio on my machine but it fails after I host it in IIS server.

Can you help me with that?

**Comment by pofider** [comment]
Could you please try to change the app pool identity to Local system?
https://forum.jsreport.net/topic/224/viewing-studio-reports-in-mvc-framework/24

**Comment by Puky96** [comment]
Thank you very much! That solved my problem!

**Comment by joaosreis** [comment]
@pofider are there any alternative solutions to this problem besides changing the App Pool Identity?

**Comment by pofider** [comment]
@joaosreis Perhaps [this thread and comment](https://forum.jsreport.net/topic/288/deploying-solution-on-windows-server/21) can help you

**Comment by pofider** [comment]
This is now solved. We place all temp files in temp folder with the latest local and binary packages.
