### ISSUE TITLE
PDF export fails with JavaScript chart when using dynamic data from ViewBag in .NET Core MVC

### ISSUE THREAD

**Issue by gokhaneryigit** [jsreport/jsreport-dotnet-example-webapp#12]
When I try to export a chart page (using JavaScript chart) to PDF in my .NET Core MVC project, it works successfully with static values. However, when I attempt to use dynamic data passed via ViewBag, the data always ends up being null, and the PDF generation fails. Does anyone know the solution to this issue?

**Comment by pofider** [comment]
Could you fork this repo and demonstrate the issue there?

**Comment by gokhaneryigit** [comment]
this is my fork https://github.com/gokhaneryigit/jsreport-dotnet-example-webapp the error on Views/Home/Chart.cshtml that i said

**Comment by gokhaneryigit** [comment]
this is my fork https://github.com/gokhaneryigit/jsreport-dotnet-example-webapp the error on Views/Home/Chart.cshtml that i said

**Comment by pofider** [comment]
Here I've fixed your asp.net razor view.
https://github.com/gokhaneryigit/jsreport-dotnet-example-webapp/pull/1

I recommend always switching to `Text` recipe when dealing with such problems. This would reveal to you what is your View producing and what is on the jsreport input.

**Comment by gokhaneryigit** [comment]
for now my codes are working. 
by the way in program.cs file 
"builder.Services.AddJsReport(new LocalReporting().UseBinary(JsReportBinary.GetBinary()).AsUtility().Create());"
instead of 
"builder.Services.AddJsReport(new LocalReporting().UseBinary(JsReportBinary.GetBinary()).KillRunningJsReportProcesses().AsUtility().Create());"
I did this and it works better.

thank you for all
