### ISSUE TITLE
How do you set page orientation?

### ISSUE THREAD

**Issue by alexsukhodolsky** [jsreport/jsreport-dotnet-example-webapp#2]
I'm pretty much using the same code as found in HomeController's InvoiceDownload method and it's working great--the pdf report is generated perfectly. But my requirements call for horizontal page orientation. 
How do I configure the page's orientation using C# code?

Thanks!
Alex

**Comment by pofider** [comment]
Try something like
```cs
HttpContext.JsReportFeature()
                .Recipe(Recipe.PhantomPdf)
                .Configure((r) => r.Template.Phantom = new Phantom { Orientation = PhantomOrientation.Landscape });
```

You can find [here](https://github.com/jsreport/jsreport-dotnet-types/blob/master/jsreport.Types/Request/Phantom.cs) or using intelisense  more options phantom recipe provides.
