### ISSUE TITLE
How to save generated reports on the webserver using webApp example?

### ISSUE THREAD

**Issue by alesshosry** [jsreport/jsreport-dotnet-example-webapp#4]
Hi, thank you for the explication and the templates. I am using jsreport in my .NET Core API; Once the client clicks on a button 'Print' , a request is sent to the API and the method takes the data in order to generate a report using JSReport and return it to the user in a view... In your template you have mentioned 2 examples: 

- One that returns the report to be displayed on the browser page:
```
[MiddlewareFilter(typeof(JsReportPipeline))]
        public IActionResult Invoice()
        {
            HttpContext.JsReportFeature().Recipe(Recipe.PhantomPdf);
            return View(InvoiceModel.Example());
        }
```

- Another that downloads the report on the client PC:
```
[MiddlewareFilter(typeof(JsReportPipeline))]
        public IActionResult InvoiceDownload()
        {
            HttpContext.JsReportFeature().Recipe(Recipe.PhantomPdf)
                .OnAfterRender((r) => HttpContext.Response.Headers["Content-Disposition"] = "attachment; filename=\"myReport.pdf\"");
            return View("Invoice", InvoiceModel.Example());
        }
```
 
But you did not mention, and I don't know if this is possible, how to save this report on the server side; In other words I need to save all my client generated reports in a directory in the webserver where the solution of my API exists; I have checked the example of consoleApp, and I know that it fits my needs by saving reports in a directory that I choose, but then I have to create 2 reports in my code: one to be returned to the client on the browser using .cshtml page as a view, and another one to download the report on my webserver using jsReport designer; But this is not the best solution for me because I will be implementing at least 20 reports in my app, then I have to create 40 reports templates in my code, and then if any modification should be implemented, changes should be applied on both templates... So is there anyway download the report directly from the controller on a specified directory on the webserver?

**Comment by pofider** [comment]
Do you want to return report to the user and at the same time save it to the disk?
The parameter in `OnAfterRender`  includes also report stream in `Content` prop. You can write it to the file 
and seek the stream back to the 0.

**Comment by alesshosry** [comment]
Yes I want to save it on the disk and return it to the user to be displayed on the browser at the same time; Any example of how to make it?

**Comment by pofider** [comment]
That seems like basic work with a stream. Please give it a try.

**Comment by alesshosry** [comment]
Ok I have changed my code to the below and it worked succesfully:

```
public IActionResult GenerateReport()
    {
                HttpContext.JsReportFeature().Recipe(Recipe.PhantomPdf)
                .Configure((r) => r.Template.Phantom = new Phantom
                {
                  Format = PhantomFormat.A4,
                  Orientation = PhantomOrientation.Portrait
                })
                .OnAfterRender((r) =>
                {
                  var streamIo = r.Content; // streamIo  is of type System.IO
                    using(var fs = System.IO.File.OpenWrite("C:GeneratedReports\\myReport.pdf"))
                    {
                      streamIo.CopyTo(fs);
                    }
                    streamIo.Seek(0, SeekOrigin.Begin);        
               }
             );

      var dp = new Classes.DataProvider();
      var lstnames = dp.GetRegisteredNames();
      var lst = lstnames.ToArray<string>();
      return View("Users", lst);

    }
```
Thank you
