### ISSUE TITLE
host js report in azure web app for conatiner

### ISSUE THREAD

**Issue by vidya091209** [jsreport/jsreport-dotnet-example-webapp#7]
I am creating a container image like this and hosting web app for container but still i am facing the issue.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
RUN apt-get update && \   
    apt-get install -y gnupg  libgconf-2-4 wget && \
    wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && \
    apt-get update && \
    apt-get install -y google-chrome-unstable --no-install-recommends

ENV chrome:launchOptions:args --no-sandbox
WORKDIR /app
EXPOSE 80
EXPOSE 443

**Comment by pofider** [comment]
Could you try the notes from here?
https://jsreport.net/learn/dotnet-local#docker

**Comment by vidya091209** [comment]
thanks its working now
